import java.util.Properties
import java.io.FileInputStream

plugins {
    id 'com.android.application'
    id 'com.google.devtools.ksp'
}

def keystorePropsFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()

if (keystorePropsFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropsFile))
}

android {
    namespace = "com.njdrive50.app"
    compileSdk = rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.njdrive50.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    aaptOptions {
        ignoreAssetsPattern = '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
    }

    signingConfigs {
        if (keystorePropsFile.exists()) {
            release {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            if (keystorePropsFile.exists()) {
                signingConfig signingConfigs.release
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
